#!/usr/bin/env python3
# btcall (29 Sep 2026, docs/android-bt-audio-20260929.md): generates the BRIDGE audio policy from the product one.
#   python3 gen-btcall-policy.py [in.xml] [out.xml]     (defaults: ../../audio_policy_configuration.xml -> ./audio_policy_configuration_btcall.xml)
#   python3 gen-btcall-policy.py --check                (exit 1 if the committed file is stale: run by tests/check-btcall.sh)
# The bridge policy = the product policy + Telephony Rx/Tx in the primary module:
#   - devices "Telephony Tx" (AUDIO_DEVICE_OUT_TELEPHONY_TX) and "Telephony Rx" (AUDIO_DEVICE_IN_TELEPHONY_RX), attached;
#   - mix ports "telephony tx" (source) / "telephony rx" (sink), 8/16 kHz mono (in-call record / in-call music front ends);
#   - device-to-device routes Telephony Rx -> Earpiece/Speaker/Wired Headset/Wired Headphones and
#     Built-In Mic/Wired Headset Mic -> Telephony Tx: calls on the phone's own devices become HW patches in the primary
#     module (the 0002 publisher reports them in vendor.a6l.audio.call_out/call_in exactly as the legacy routing);
#   - Telephony Rx -> "telephony rx" and "telephony tx" -> Telephony Tx: the audio policy can only reach the BT SCO
#     devices of the "bluetooth" module through these, so it builds the AudioFlinger SOFTWARE bridge
#     (Telephony Rx -> record thread -> hfp output -> BT SCO; BT SCO Headset Mic -> hfp input -> playback thread ->
#     Telephony Tx). The HAL opens real PCMs for these streams only with persist.vendor.a6l.btcall.bridge=1 (patch 0004).
# Installed as /vendor/etc/audio_policy_configuration_btcall.xml; init.a6l.btcall.rc bind-mounts it over the product
# policy at early-boot when persist.vendor.a6l.btcall.bridge=1 (default: not mounted = today's policy).
import os, sys

H = os.path.dirname(os.path.abspath(__file__))
IN = os.path.join(H, "../../audio_policy_configuration.xml")
OUT = os.path.join(H, "audio_policy_configuration_btcall.xml")
PROF_OUT = '<profile name="" format="AUDIO_FORMAT_PCM_16_BIT"\n                             samplingRates="8000 16000" channelMasks="AUDIO_CHANNEL_OUT_MONO"/>'
PROF_IN = '<profile name="" format="AUDIO_FORMAT_PCM_16_BIT"\n                             samplingRates="8000 16000" channelMasks="AUDIO_CHANNEL_IN_MONO"/>'


def gen(src):
    s = src.replace("\r\n", "\n")
    a = s.index('<module name="primary"')
    b = s.index("</module>", a)
    m = s[a:b]

    def ins_after(block, anchor, text):
        i = block.index(anchor) + len(anchor)
        return block[:i] + text + block[i:]

    def ins_before(block, anchor, text):
        i = block.index(anchor)
        return block[:i] + text + block[i:]

    m = ins_before(m, "            </attachedDevices>",
                   "                <!-- btcall: modem call audio as devices (bridge policy) -->\n"
                   "                <item>Telephony Tx</item>\n                <item>Telephony Rx</item>\n")
    m = ins_before(m, "            </mixPorts>",
                   "                <!-- btcall: AudioFlinger software bridge streams (HAL patch 0004: in-call music / in-call\n"
                   "                     record front ends, persist.vendor.a6l.btcall.ul_pcm / dl_pcm) -->\n"
                   '                <mixPort name="telephony tx" role="source">\n                    ' + PROF_OUT.replace("\n                             ", "\n                             ") + "\n"
                   "                </mixPort>\n"
                   '                <mixPort name="telephony rx" role="sink">\n                    ' + PROF_IN + "\n"
                   "                </mixPort>\n")
    m = ins_before(m, "            </devicePorts>",
                   '                <devicePort tagName="Telephony Tx" type="AUDIO_DEVICE_OUT_TELEPHONY_TX" role="sink">\n                    ' + PROF_OUT + "\n"
                   "                </devicePort>\n"
                   '                <devicePort tagName="Telephony Rx" type="AUDIO_DEVICE_IN_TELEPHONY_RX" role="source">\n                    ' + PROF_IN + "\n"
                   "                </devicePort>\n")
    for sink in ("Earpiece", "Speaker", "Wired Headset", "Wired Headphones"):
        old = f'<route type="mix" sink="{sink}" sources="primary output"/>'
        assert m.count(old) == 1, old
        m = m.replace(old, f'<route type="mix" sink="{sink}" sources="primary output,Telephony Rx"/>')
    m = ins_before(m, "            </routes>",
                   "                <!-- btcall: calls on the phone = HW patches; to another module (BT SCO) = software bridge -->\n"
                   '                <route type="mix" sink="Telephony Tx" sources="telephony tx,Built-In Mic,Wired Headset Mic"/>\n'
                   '                <route type="mix" sink="telephony rx" sources="Telephony Rx"/>\n')
    head = ("<!-- GENERATED by audio/bluetooth/btcall/gen-btcall-policy.py from audio/audio_policy_configuration.xml: do not edit,\n"
            "     regenerate. btcall bridge policy (docs/android-bt-audio-20260929.md), active only when init.a6l.btcall.rc\n"
            "     bind-mounts it over /vendor/etc/audio_policy_configuration.xml (persist.vendor.a6l.btcall.bridge=1 at boot). -->\n")
    out = s[:a] + m + s[b:]
    i = out.index("?>") + 2 + 1  # after the XML declaration line
    return out[:i] + head + out[i:]


if __name__ == "__main__":
    if sys.argv[1:] == ["--check"]:
        want = gen(open(IN).read())
        have = open(OUT).read().replace("\r\n", "\n") if os.path.exists(OUT) else ""
        print("BTCALL_POLICY " + ("UP_TO_DATE" if want == have else "STALE (run gen-btcall-policy.py)"))
        sys.exit(0 if want == have else 1)
    src = sys.argv[1] if len(sys.argv) > 1 else IN
    dst = sys.argv[2] if len(sys.argv) > 2 else OUT
    open(dst, "w").write(gen(open(src).read()))
    print("written", dst)
