#!/usr/bin/env python3
"""Generate SDM660 CPRh nvmem cells + OPP tables (DT overlay) from the stock
kernel fuse tables (dumped from stock-symbolized.elf, see
research/rest-20260924/cprh-sdm660-fuse-tables.txt) and the stock DT
(cprh-ctrl@179c8000/179c4000, qcom,clk-cpu-660@179c0000).
Layout verified on msm8998: {row,start,end} -> qfprom byte 0x4000+row*8+start//8
relative to qfprom@780000 (mainline) == 0x784000 + row*8 (stock fuse_base)."""
QF = 0x4000
# [cluster][fuse corner] ; cluster 0 = pwrcl (apc0), 1 = perfcl (apc1)
ro_sel = [[(67,12,15),(67,8,11),(65,56,59),(67,4,7),(67,0,3)],
          [(68,61,63,69,0,0),(69,1,4),(68,57,60),(68,53,56),(66,14,17)]]
init_v = [[(67,34,39),(67,28,33),(71,3,8),(67,22,27),(67,16,21)],
          [(69,17,22),(69,23,28),(69,11,16),(69,5,10),(70,42,47)]]
quot   = [[(68,12,23),(68,0,11),(71,9,20),(67,52,63),(67,40,51)],
          [(69,53,63,70,0,0),(70,1,12),(69,41,52),(69,29,40),(70,48,59)]]
qoff   = [[None,(68,38,44),(71,21,27),(68,31,37),(68,24,30)],
          [None,(70,27,33),(70,20,26),(70,13,19),(70,60,63,71,0,2)]]
speed_bin = (38,29,31)
fuse_rev = (71,28,30)

def cell(label, name, p):
    row, s, e = p[0], p[1], p[2]
    width = e - s + 1
    if len(p) == 6:                       # continues into next row from bit 0
        assert p[3] == row + 1 and p[4] == 0 and s + width == 64
        width += p[5] - p[4] + 1
    bit = row * 64 + s
    off = QF + bit // 8
    b = bit % 8
    nbytes = (b + width + 7) // 8
    return (f"\t\t{label}: {name}@{off:x} {{\n\t\t\treg = <0x{off:x} 0x{nbytes:x}>;\n"
            f"\t\t\tbits = <{b} {width}>;\n\t\t}};\n")

cells, refs, names = [], [], []
cells.append(cell("cpr_efuse_speedbin", "cpr-speedbin", speed_bin)); refs.append("cpr_efuse_speedbin"); names.append("cpr_speed_bin")
cells.append(cell("cpr_fuse_revision", "cpr-fusing-rev", fuse_rev)); refs.append("cpr_fuse_revision"); names.append("cpr_fuse_revision")
for c, cl in enumerate(("pwrcl", "perfcl")):
    for kind, tab, nm in (("quot", quot, "quotient"), ("qoff", qoff, "quotient_offset"),
                          ("ivolt", init_v, "init_voltage"), ("rosel", ro_sel, "ring_osc")):
        for fc in range(5):
            p = tab[c][fc]
            if p is None:
                continue
            lab = f"cpr_{kind}{fc}_{cl}"
            cells.append(cell(lab, f"{kind}{fc}-{cl}", p))
            refs.append(lab); names.append(f"cpr{c}_{nm}{fc+1}")

# stock clk-cpu-osm speedbin rows: <freq freq_data override spare corner>
pwr_rows = [(300000000,0x4000f,0x1200020,1,1),(633600000,0x5040021,0x3200020,1,2),
            (902400000,0x404002f,0x4260026,1,3),(1113600000,0x404003a,0x52e002e,2,4),
            (1401600000,0x4040049,0x73a003a,2,5),(1536000000,0x4040050,0x8400040,2,6),
            (1747200000,0x404005b,0x9480048,2,7),(1843200000,0x4040060,0x94c004c,3,8)]
perf_rows = [(300000000,0x4000f,0x1200020,1,1),(1113600000,0x404003a,0x52e002e,1,2),
             (1401600000,0x4040049,0x73a003a,2,3),(1747200000,0x404005b,0x9480048,2,4),
             (1958400000,0x4040066,0xa510051,2,5),(2150400000,0x4040070,0xb590059,2,6),
             (2208000000,0x4040073,0xb5c005c,3,7)]
# first bring-up: frequencies common to speed bins 0/1/3/4 only
PWR_MAX, PERF_MAX = 1536000000, 1747200000
pwr_fmax = [2,3,4,5,8]; perf_fmax = [2,3,4,6,7]
def fuse_level(corner, fmax):
    for i, f in enumerate(fmax):
        if corner <= f:
            return i + 1
    return len(fmax)

o = []
o.append("// SPDX-License-Identifier: GPL-2.0-only\n// GENERATED by gen_sdm660_cpr.py - A6L CPRh + OSM cpufreq (OPEN-LOOP bring-up). VOLTAGE-AFFECTING: attended only.\n/dts-v1/;\n/plugin/;\n\n#include <dt-bindings/clock/qcom,gcc-sdm660.h>\n#include <dt-bindings/clock/qcom,rpmcc.h>\n#include <dt-bindings/power/qcom-rpmpd.h>\n\n")
o.append("&qfprom {\n" + "".join(c.replace("\t\t", "\t", 1).replace("\n\t\t\t", "\n\t\t").replace("\n\t\t};", "\n\t};") for c in cells) + "};\n\n")
o.append("&{/} {\n\tcprh_opp_table: opp-table-cprh {\n\t\tcompatible = \"operating-points-v2-qcom-level\";\n\t\topp-shared;\n")
for lvl in range(1, 9):
    o.append(f"\t\tcprh_opp{lvl}: opp-{lvl} {{\n\t\t\topp-level = <{lvl}>;\n"
             f"\t\t\tqcom,opp-fuse-level = <{fuse_level(lvl, pwr_fmax)} {fuse_level(min(lvl,7), perf_fmax)}>;\n"
             f"\t\t\tqcom,opp-cloop-vadj = <0 0>;\n\t\t\tqcom,opp-oloop-vadj = <0 0>;\n\t\t}};\n")
o.append("\t};\n\n")
for tname, rows, fmax in (("pwrcl_opp_table", pwr_rows, PWR_MAX), ("perfcl_opp_table", perf_rows, PERF_MAX)):
    o.append(f"\t{tname}: opp-table-{tname.split('_')[0]} {{\n\t\tcompatible = \"operating-points-v2\";\n\t\topp-shared;\n")
    for f, fd, ov, sp, corner in rows:
        if f > fmax:
            continue
        div = (fd >> 24) & 3
        o.append(f"\t\topp-{f} {{\n\t\t\topp-hz = /bits/ 64 <{f}>;\n\t\t\trequired-opps = <&cprh_opp{corner}>;\n"
                 f"\t\t\tqcom,pll-override = <0x{ov:x}>;\n\t\t\tqcom,spare-data = <{sp}>;\n")
        if div:
            o.append(f"\t\t\tqcom,pll-div = <{div}>;\n")
        o.append("\t\t};\n")
    o.append("\t};\n\n")
o.append("""};

&soc {
	cpufreq_hw: cpufreq@179c1000 {
		compatible = "qcom,sdm660-cpufreq-hw";
		reg = <0x179c1000 0x1000>, <0x179c3000 0x1000>,
		      <0x179c0000 0x1000>, <0x179c2000 0x1000>;
		reg-names = "freq-domain0", "freq-domain1",
			    "osm-domain0", "osm-domain1";
		clocks = <&rpmcc RPM_SMD_XO_A_CLK_SRC>, <&gcc HMSS_GPLL0_CLK_SRC>;
		clock-names = "xo", "alternate";
		assigned-clocks = <&gcc HMSS_GPLL0_CLK_SRC>;
		assigned-clock-rates = <300000000>;
		#freq-domain-cells = <1>;
		#clock-cells = <1>;
	};

	apc_cprh: power-controller@179c8000 {
		compatible = "qcom,sdm660-cprh", "qcom,cprh";
		reg = <0x179c8000 0x4000>, <0x179c4000 0x4000>;
		clocks = <&gcc GCC_HMSS_RBCPR_CLK>;
		assigned-clocks = <&gcc GCC_HMSS_RBCPR_CLK>;
		assigned-clock-rates = <19200000>;
		operating-points-v2 = <&cprh_opp_table>;
		power-domains = <&rpmpd SDM660_VDDCX_AO>;
		#power-domain-cells = <1>;
		nvmem-cells = """ + ",\n\t\t\t      ".join(f"<&{r}>" for r in refs) + """;
		nvmem-cell-names = """ + ",\n\t\t\t\t   ".join(f'"{n}"' for n in names) + """;
	};
};

""")
# sdm630.dtsi: cpu0-3 = cpu@100 (perf cluster, OSM domain 1, CPR thread 1); cpu4-7 = cpu@0 (pwr cluster, domain 0, thread 0)
for i in range(8):
    perf = i < 4
    o.append(f"&cpu{i} {{\n\toperating-points-v2 = <&{'perfcl' if perf else 'pwrcl'}_opp_table>;\n"
             f"\tpower-domains = <&apc_cprh {1 if perf else 0}>;\n\tpower-domain-names = \"perf\";\n"
             f"\tqcom,freq-domain = <&cpufreq_hw {1 if perf else 0}>;\n}};\n\n")
open("a6l-cpufreq-v75.dtso", "w").write("".join(o))
print("cells:", len(refs))
