# SPDX-License-Identifier: Apache-2.0
# Compile probe: upstream arm64 GSI board, not yet a native A6L board.
include build/make/target/board/generic_arm64/BoardConfig.mk

# Actual A6L system partition capacity from the verified GPT.
BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE :=
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 6442450944

# No boot/recovery/kernel output from this initial system-only probe.
TARGET_NO_KERNEL := true
TARGET_NO_RECOVERY := true
# 21 Sep 2026: RAM-delivered system image for the real-init boot flow (labeled, read-only, compressed).
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_EROFS_COMPRESSOR := lz4hc
BOARD_EROFS_PCLUSTER_SIZE := 65536
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := erofs
TARGET_COPY_OUT_VENDOR := vendor
# 24 Sep 2026 (flash, rom-v1): real stock vendor partition size (GPT: 1100 MiB); rom-v1 adds firmware/modules/Mesa.
BOARD_VENDORIMAGE_PARTITION_SIZE := 1153433600
# 23 Sep 2026 (realinit2): minimal device VINTF manifest (HAL fragments come with the modules; assemble_vintf
# fills target-level from PRODUCT_SHIPPING_API_LEVEL and the sepolicy version).
DEVICE_MANIFEST_FILE := device/hisense/a6l/manifest.xml
# 24 Sep 2026 (flash, rom-v1): kernel modules, remote-processor firmware and the Mesa libs are staged as prebuilt
# PRODUCT_COPY_FILES (device/hisense/a6l/rom/rom-files.mk); they are ELF files.
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
# rom-v1 variant board flags (generated by tools/rom-v1-pipeline.sh; empty for the base variant)
-include device/hisense/a6l/rom/variant/BoardConfig-variant.mk
# rom-v2 (agent merge, 25 Sep 2026): Wi-Fi flags, per-area sepolicy, GApps board flags
-include device/hisense/a6l/rom/BoardConfig-rom.mk
# release-prep (27 Sep 2026): release board flags (recovery, OTA, no AVB) ONLY with A6L_RELEASE=1 in the build environment
# (docs/release-prep-20260927.md). Unset = the r1-r3 configuration, byte-for-byte.
ifeq ($(A6L_RELEASE),1)
include device/hisense/a6l/rom/release/BoardConfig-release.mk
endif
