# SPDX-License-Identifier: Apache-2.0
# Deliberately reuse the upstream LineageOS 24 GSI architecture while assessing
# the A6L's Android 9 vendor compatibility. This is not a deployable native port.
$(call inherit-product, vendor/lineage/build/target/product/lineage_gsi_arm64.mk)

PRODUCT_NAME := lineage_gsi_a6l
PRODUCT_DEVICE := a6l
PRODUCT_BRAND := Hisense
PRODUCT_MANUFACTURER := Hisense
PRODUCT_MODEL := A6L bringup probe

# The real device has fixed GPT partitions and no super partition. Do not make
# unrelated images or an OTA. Preserve upstream GSI shipping API semantics;
# the actual stock shipping API is recorded separately in hardware.json.
PRODUCT_USE_DYNAMIC_PARTITIONS := false
PRODUCT_USE_DYNAMIC_PARTITION_SIZE := false
PRODUCT_BUILD_BOOT_IMAGE := false
PRODUCT_BUILD_RECOVERY_IMAGE := false
# 21 Sep 2026: real-init flow needs /vendor/etc/selinux (split policy) and a labeled vendor image
PRODUCT_BUILD_VENDOR_IMAGE := true
PRODUCT_BUILD_USERDATA_IMAGE := false
PRODUCT_BUILD_SUPER_PARTITION := false
PRODUCT_BUILD_SUPER_EMPTY_IMAGE := false
PRODUCT_BUILD_PVMFW_IMAGE := false
TARGET_FORCE_OTA_PACKAGE := false

# 23 Sep 2026 (realinit2): the real-init flow needs vendor HALs *inside* vendor.img (r24: keystore2 aborts with
# "Trying to construct mandatory security level TEE"; servicemanager finds no vendor VINTF manifest). The HALs were
# only in the staging dir (built by name), not packaged. Software graphics stack for the VM/phone RAM bring-up.
$(call inherit-product, device/hisense/a6l/a6l-software-graphics.mk)
PRODUCT_PACKAGES += \
    android.hardware.security.keymint-service.nonsecure \
    android.hardware.health-service.example \
    com.android.hardware.audio \
    vndservicemanager

# r26 (realinit2): audioserver SIGSEGVs in AudioFlinger::onFirstRef without an audio HAL. The AIDL example audio HAL
# (vendor APEX) is selected by androidboot.vendor.apex.com.android.hardware.audio (the launcher adds it to the cmdline).
# r27: the AIDL example effect HAL exits 1 ("audio_effects_config.xml not found"), its onrestart kills the audio HAL and
# audioserver in a loop, and system_server's AudioService constructor then blocks until the Watchdog kills it.
# r28 (realinit2) -> r29 (realinit3): the frameworks/av audio_effects.xml pointed at /vendor/lib64/soundfx libs that do not
# exist; use the AIDL example effect config instead (its libs are inside the com.android.hardware.audio APEX), as cuttlefish does.
# The AIDL example core HAL registered IConfig/default but no IModule ("No audio configuration files found"): ship a minimal
# 7.0 audio policy configuration with a primary module (speaker + built-in mic) under /vendor/etc.
$(call inherit-product, hardware/interfaces/audio/aidl/default/audio_effects.mk)
PRODUCT_COPY_FILES += \
    device/hisense/a6l/audio/realinit/audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration.xml \
    frameworks/av/services/audiopolicy/config/audio_policy_volumes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_volumes.xml \
    frameworks/av/services/audiopolicy/config/default_volume_tables.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default_volume_tables.xml

# 24 Sep 2026 (flash): installable rom-v1 = fstab/init/ueventd for the real partitions, module loader, firmware, radio
# daemons, e-ink payload, Mesa. See docs/flash-20260924.md.
$(call inherit-product, device/hisense/a6l/rom/rom.mk)
# rom-v1 variant (base = empty, full = audio3 + hals subset): generated by tools/rom-v1-pipeline.sh
-include device/hisense/a6l/rom/variant/variant.mk
