#!/usr/bin/env python3
# volte4 (27 Sep 2026): build the EFS item patch profiles for step A (IMS on under the ROW_Commercial SW MBN).
# Source of truth = the stock MBNs of the A6L's own modem image (same MPSS build, so every item path/size is one
# this modem understands). The last occurrence of a path in an MBN wins (that is how MCFG applies them: e.g. ROW sets
# IMS_enable=1 at item 73 and IMS_enable=0 again at item 92).
# usage: mk_nv_patch.py <MCFG_SW dir> <outdir>
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mcfg_items as m

SCOPE = ('/nv/item_files/ims/', '/nv/item_files/modem/mmode/', '/nv/item_files/modem/nas/')

def last_values(path):
    info, items = m.parse(path)
    v = {}
    for it in items:
        if it['kind'] == 'efs' and it.get('has_data') and it['path']:
            v[it['path']] = it['data']
    return info, v

def write(fn, header, entries):
    with open(fn, 'w') as f:
        f.write(header)
        for p, h, why in entries:
            f.write('# %s\n' % why)
            f.write('put %s %s\n' % (p, h))
    print('wrote %s (%d items)' % (fn, len(entries)))

def main():
    base, out = sys.argv[1], sys.argv[2]
    os.makedirs(out, exist_ok=True)
    row_i, row = last_values(os.path.join(base, 'GENERIC/COMMON/ROW/COMMERCI/MCFG_SW.MBN'))
    ora_i, ora = last_values(os.path.join(base, 'GENERIC/EU/ORANGE/COMMERCI/FRANCE/MCFG_SW.MBN'))
    hdr = ('# a6l-volte-cfg EFS item patch (volte4, generated by tools/volte4/mk_nv_patch.py, do not edit by hand)\n'
           '# format: put <efs path> <hex content>   (content = the EFS item bytes, MCFG subscription prefix removed)\n'
           '# base (active on the phone): %s %s ; values from: %s %s\n' % (row_i.get('name'), row_i.get('version'),
                                                                          ora_i.get('name'), ora_i.get('version')))
    a1 = [('/nv/item_files/ims/IMS_enable', '01', 'ROW sets 00 (its item 92); Orange FR sets 01')]
    write(os.path.join(out, 'a1-ims-enable.nvp'), hdr + '# A1: only switch the modem IMS stack on (ROW keeps its generic IMS settings)\n', a1)
    a2 = list(a1)
    for p in sorted(ora):
        if not p.startswith(SCOPE) or p == '/nv/item_files/ims/IMS_enable':
            continue
        if row.get(p) == ora[p]:
            continue
        why = 'ROW=%s' % ('absent' if p not in row else (row[p] if len(row[p]) <= 16 else '%d B' % (len(row[p]) // 2)))
        why += ' Orange=%s' % (ora[p] if len(ora[p]) <= 16 else '%d B' % (len(ora[p]) // 2))
        a2.append((p, ora[p], why))
    write(os.path.join(out, 'a2-ims-orange.nvp'), hdr + '# A2: A1 + every Orange FR IMS / mmode / NAS item that differs from ROW\n', a2)

if __name__ == '__main__':
    main()
