#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate einklock_font.h: the pre-rasterised glyphs of the e-ink lock screen (a6l_einklock).

The vendor daemon has no font engine (no freetype in vendor, no GPU while the phone sleeps), so the three faces it needs
are rasterised once here, on the host, from the Roboto variable font of the Android tree (Apache-2.0 / OFL, see
external/roboto-fonts/NOTICE), and committed as 4-bit alpha, run-length encoded:
  clock : weight 300, 240 px, "0123456789:"            (the big HH:MM; Roboto digits are tabular = no jitter)
  text  : weight 400,  52 px, U+0020-007E + U+00A0-00FF (date line; Latin-1 covers en/fr/de/es/it/pt)
  small : weight 400,  38 px, same set                   (battery, owner message, AM/PM)
RLE byte = (run - 1) << 4 | alpha4, run 1..16; alpha4 * 17 = 8-bit coverage. Glyph origin = left end of the baseline.
usage: gen_einklock_font.py [ROBOTO_TTF] > einklock_font.h
"""
import sys
from PIL import Image, ImageDraw, ImageFont

TTF = sys.argv[1] if len(sys.argv) > 1 else "/home/a6l/android/a6l-lineage24/external/roboto-fonts/font/3.015/Roboto-Regular.ttf"
LATIN = [c for c in range(0x20, 0x7F)] + [c for c in range(0xA0, 0x100)]
FACES = [("clock", 300, 240, [ord(c) for c in "0123456789:"]),
         ("text", 400, 52, LATIN),
         ("small", 400, 38, LATIN)]

def rle(vals):
    out = bytearray(); i = 0
    while i < len(vals):
        j = i
        while j < len(vals) and j - i < 16 and vals[j] == vals[i]: j += 1
        out.append(((j - i - 1) << 4) | vals[i]); i = j
    return out

data = bytearray(); faces = []
for name, weight, size, cps in FACES:
    f = ImageFont.truetype(TTF, size)
    try: f.set_variation_by_axes([weight, 100, 0])
    except Exception: pass
    asc, desc = f.getmetrics()
    glyphs = []
    for cp in cps:
        ch = chr(cp); adv = int(round(f.getlength(ch)))
        l, t, r, b = f.getbbox(ch, anchor="ls")
        w, h = max(0, r - l), max(0, b - t)
        if w == 0 or h == 0:
            glyphs.append((cp, 0, 0, 0, 0, adv, len(data), 0)); continue
        im = Image.new("L", (w, h), 0)
        ImageDraw.Draw(im).text((-l, -t), ch, font=f, fill=255, anchor="ls")
        q = [(p * 15 + 127) // 255 for p in im.getdata()]
        enc = rle(q); off = len(data); data.extend(enc)
        assert w < 256 and h < 256 and adv < 256 and len(enc) < 65536, (name, cp)
        glyphs.append((cp, w, h, l, t, adv, off, len(enc)))
    faces.append((name, asc, desc, glyphs))

o = sys.stdout
o.write("// SPDX-License-Identifier: Apache-2.0\n/* GENERATED by tools/gen_einklock_font.py from Roboto (Apache-2.0, external/roboto-fonts). Do not edit.\n"
        " * 4-bit alpha, RLE: byte = (run-1)<<4 | alpha4. Included only by einklock_logic.c. */\n#pragma once\n#include <stdint.h>\n")
o.write("struct elk_glyph { uint16_t cp; uint8_t w, h; int16_t xoff, yoff; uint8_t adv; uint32_t off; uint16_t len; };\n")
o.write("struct elk_font { const struct elk_glyph *g; int n; int ascent, descent; };\n")
o.write("static const uint8_t elk_font_data[%d] = {\n" % len(data))
for i in range(0, len(data), 24):
    o.write("    " + ",".join("0x%02x" % b for b in data[i:i + 24]) + ",\n")
o.write("};\n")
for name, asc, desc, glyphs in faces:
    o.write("static const struct elk_glyph elk_glyphs_%s[%d] = {\n" % (name, len(glyphs)))
    for g in glyphs: o.write("    {0x%04x, %d, %d, %d, %d, %d, %d, %d},\n" % g)
    o.write("};\n")
    o.write("static const struct elk_font elk_font_%s = { elk_glyphs_%s, %d, %d, %d };\n" % (name, name, len(glyphs), asc, desc))
