#!/usr/bin/env bash
# Stage the rom-v1 vendor prebuilts into the Lineage tree (agent flash, 24 Sep 2026). WSL only. No build, no phone.
# Sources = the payloads PROVEN from RAM on the phone (laptop bundles fetched to /home/a6l/rom-v1/src by flash-08) + the
# Mesa libs of the V71 phone framework payload + the repo device/hisense/a6l/rom files.
# Output: $L/device/hisense/a6l/rom/{prebuilt/vendor/..., rom-files.mk, ...} and a manifest with every file's sha256.
set -euo pipefail
R=/mnt/c/Users/Pierre/Desktop/A6L; L=/home/a6l/android/a6l-lineage24; S=/home/a6l/rom-v1/src
T=$L/device/hisense/a6l/rom; P=$T/prebuilt/vendor; MAN=/home/a6l/rom-v1/prebuilt-manifest.txt
P72=/home/a6l/flash-scratch/p72/root/vendor
rm -rf $T; mkdir -p $T; cp -r $R/device/hisense/a6l/rom/. $T/; rm -rf $T/prebuilt; mkdir -p $P/lib/modules $P/firmware $P/etc/a6l/modules $P/a6l/radio/bin $P/a6l/epd $P/a6l/tools $P/lib64/egl
find $T -name '*.sh' -o -name '*.rc' -o -name '*.mk' -o -name '*.txt' -o -name 'fstab.qcom' | xargs sed -i 's/\r$//'
: > $T/conflicts.txt
addko() { # file (first copy wins; identical duplicates are fine; different bytes are recorded)
  local f=$1 n; n=$(basename $f)
  if [ -e $P/lib/modules/$n ]; then cmp -s $f $P/lib/modules/$n || echo "CONFLICT $n kept=$(sha256sum < $P/lib/modules/$n | cut -c1-16) ignored=$(sha256sum < $f | cut -c1-16) from $f" >> $T/conflicts.txt
  else cp $f $P/lib/modules/$n; fi; }
# priority: display (bundle-v74) > touch > sensors-adsp > adsp(v68) > audio2 > als2 > radio2 > radio2 bt
for f in $S/v74_bundle-v74/modules/*.ko $S/v71_bundle_touch/modules/*.ko $S/v71_bundle_sensors-adsp/modules/*.ko $S/v68_bundle_adsp/modules/*.ko \
         $S/v74_audio2/modules/*.ko $S/v74_als2/modules/*.ko $S/v74_radio2/modules/*.ko $S/v74_radio2/modules-bt/*.ko; do addko $f; done
cp $R/firmware/extracted/phone-kernel-v67-candidate-20260919/a6l_simplefb.ko $P/lib/modules/
# every module listed must exist
for l in $T/modules/*.txt; do cp $l $P/etc/a6l/modules/; grep -v '^#' $l | awk 'NF{print $1}' | while read -r k; do [ -e $P/lib/modules/$k ] || { echo "MISSING $k in $(basename $l)"; exit 1; }; done; done
[ -e $P/lib/modules/tmd3702.ko ] && [ -e $P/lib/modules/a6l_simplefb.ko ]
# vermagic: all modules must match the phone kernel
bad=0; for k in $P/lib/modules/*.ko; do v=$(strings $k | grep '^vermagic=' | sed -n 1p || true); case "$v" in "vermagic=7.2.3-a6l-probe+ "*) ;; *) echo "VERMAGIC $k $v"; bad=1;; esac; done; [ $bad = 0 ]
# firmware (tree relative to firmware_class.path=/vendor/firmware)
cp -r $S/v74_bundle-v74/firmware/. $P/firmware/
cp -r $S/v74_radio2/firmware/. $P/firmware/
mkdir -p $P/firmware/qcom/hisense/a6l $P/firmware/qcom/sensors
cp $S/v68_bundle_adsp/firmware/adsp.* $P/firmware/qcom/hisense/a6l/
cp $S/v71_bundle_sensors-adsp/firmware/qcom/sensors/sns.reg $P/firmware/qcom/sensors/
# radio userspace exactly as proven (run with LD_LIBRARY_PATH=/vendor/a6l/radio/bin)
cp $S/v74_radio2/bin/* $P/a6l/radio/bin/
# e-ink payload (manual/attended use: a6l_epdd_v2/v3, mirror, stock TCON lib + panel waveform)
cp -r $S/v74_bundle-v74/epd/. $P/a6l/epd/
cp $S/v74_eink-mirror/a6l_epdd_v3 $S/v74_eink-mirror/a6l_eink_mirror $S/v74_eink-mirror/eink-mirror-session.sh $P/a6l/epd/
cp $S/v74_eink3/a6l_lease_probe $S/v74_eink3/eink3-session.sh $P/a6l/epd/ 2>/dev/null || true
# attended test tools
cp $S/v74_bundle-v74/bin/* $P/a6l/tools/; cp $S/v74_audio2/bin/* $P/a6l/tools/
cp -r $S/v74_audio2/mixer2 $S/v74_audio2/wav $P/a6l/tools/
# Mesa freedreno (V71 phone framework payload, proven with the LineageOS UI on 21 Sep)
cp $P72/lib64/egl/libEGL_mesa.so $P72/lib64/egl/libGLESv1_CM_mesa.so $P72/lib64/egl/libGLESv2_mesa.so $P/lib64/egl/
cp $P72/lib64/libgallium_dri.so $P/lib64/
# laptop adb key (attended debugging from the first boot)
cp $R/firmware/extracted/laptop-adb-public-key.txt $P/etc/a6l/adb_keys
# rom-files.mk
( cd $T/prebuilt/vendor && find . -type f | sed 's#^\./##' | sort ) | awk -v D=device/hisense/a6l/rom/prebuilt/vendor '
  BEGIN{print "# generated by tools/stage-rom-v1-prebuilts.sh - do not edit"; print "PRODUCT_COPY_FILES += \\"}
  {printf "    %s/%s:$(TARGET_COPY_OUT_VENDOR)/%s \\\n", D, $0, $0} END{print ""}' > $T/rom-files.mk
( cd $T && find . -type f ! -name prebuilt-manifest.txt | sort | xargs sha256sum ) > $MAN
echo "files: $(wc -l < $MAN)  size: $(du -sh $T/prebuilt | cut -f1)  conflicts: $(wc -l < $T/conflicts.txt)"
cat $T/conflicts.txt | head -20
echo "== mesa NEEDED"; for f in $P/lib64/libgallium_dri.so $P/lib64/egl/libEGL_mesa.so; do readelf -d $f | grep NEEDED | tr -s ' ' | cut -d' ' -f6 | tr '\n' ' '; echo; done
echo STAGE_ROM_V1_PREBUILTS_PASS
